# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

env:
  global:
    # Use non-interactive backend
    - MPLBACKEND: Agg
    - CYTHON_TRACE: 1

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - NUMPYSPEC=numpy
        - MATPLOTLIBSPEC=matplotlib
        - CYTHONSPEC=cython
        - USE_WHEEL=1
    - os: linux
      python: 3.7
      dist: xenial # travis-ci/travis-ci/issues/9815
      sudo: true
      env:
        - NUMPYSPEC=numpy
        - MATPLOTLIBSPEC=matplotlib
        - CYTHONSPEC=cython
        - USE_SDIST=1
        - USE_SCIPY=1
    - os: linux
      python: 3.5
      env:
        - NUMPYSPEC="numpy==1.13.3"
        - MATPLOTLIBSPEC=matplotlib
        - CYTHONSPEC="cython==0.23.5"
        - REFGUIDE_CHECK=1  # run doctests only
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env:
        - NUMPYSPEC=numpy
        - MATPLOTLIBSPEC=matplotlib
        - CYTHONSPEC=cython
        - TRAVIS_PYTHON_VERSION=3.5

cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source util/travis_osx_install.sh; fi
  - ccache -s
  - which python; python --version
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  - pip install $NUMPYSPEC
  - pip install $MATPLOTLIBSPEC
  - pip install $CYTHONSPEC
  - pip install pytest pytest-cov coverage codecov futures
  - set -o pipefail
  - if [ "${USE_WHEEL}" == "1" ]; then pip install wheel; fi
  - if [ "${USE_SCIPY}" == "1" ]; then pip install scipy; fi
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install sphinx numpydoc
    fi

script:
  # Define a fixed build dir so next step works
  - |
    if [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        pip wheel . -v
        pip install PyWavelets*.whl -v
        pushd demo
        pytest --pyargs pywt
        python ../pywt/tests/test_doc.py
        popd
    elif [ "${USE_SDIST}" == "1" ]; then
        python setup.py sdist
        # Move out of source directory to avoid finding local pywt
        pushd dist
        pip install PyWavelets* -v
        pytest --pyargs pywt
        python ../pywt/tests/test_doc.py
        popd
    elif [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install -e . -v
        python util/refguide_check.py --doctests
    else
        CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        CFLAGS="--coverage" pip install -e . -v
        pushd demo
        pytest --pyargs pywt --cov=pywt
        popd
    fi

after_success:
  - codecov
  # Travis CI has old gcov, needs object dir explicitly specified
  - gcov --object-directory build/tmp/pywt/_extensions/c/ build/tmp/pywt/_extensions/c/*.o
  - bash <(curl -s https://codecov.io/bash)
